title: AICRV 2026
preposition: at
description: >-
  The international AI, computer vision, and robotics held in Canada  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://example.com" # the base hostname & protocol for your site, e.g. https://example.com

# theme: jekyll-theme-conference


# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+02:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Canadian Conference on AI, CV & Robotics
      # img: ''
      url: 'https://aicrv.github.io'
    breakpoint: md
    links:
      - name: Call for Workshops
        relative_url: /workshops/
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2026 (current)
            disabled: true

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
        disabled: true
      - name: How to get there
        relative_url: /location/
        disabled: true
      - name: Tickets
        disabled: true
        absolute_url: ''

  # Information boxes
  info_bars:
    - title: The Call for Workshops is now Live!
      color: primary
      main_only: true
      text: |
        See [here](workshops/) for details!
 #   - text: This is just some random content for demonstration purposes.
 #     color: warning
 #     pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop: 240 # in minutes
    streaming:
      enable: true
      pause: 60 # in minutes
      prepend: 5 # in minutes
      extend: 5 # in minutes
    demo:
      enable: false
      duration: 300 # in seconds
      pause: 10 # in seconds

  talks:
    # Talk tracks
    tracks:
      - name: Track A
        color: info
      - name: Track B
        color: success

    # Talk tags
    tags:
      - name: No recording
        icon: video-slash

    # Hide icons on talk overview page
    hide_link_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 49.2791, -122.9202
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
